/**
 * Sit and watch a recorded game run through a real room.
 *
 * Three visible browsers, a real room, a real replay, and a transcript written
 * as it goes. The windows are for the feel of it; **the transcript is the
 * validation artifact**, and it is the more important of the two.
 *
 * Usage — the server must already be running with the replay seam on:
 *
 *   ALLOW_REPLAY_ATTACH=1 PORT=3002 node server.js
 *   node scripts/watch-replay.mjs fixtures/nfl/401772879.json
 *   node scripts/watch-replay.mjs fixtures/nfl/401772879.json --speed 20
 *
 * Ctrl-C, or closing a window, ends it.
 *
 * ── On the transcript ─────────────────────────────────────────────────────
 *
 * One line per PLAY, not per detection, and every play in the fixture whether
 * or not it produced anything. The blank lines are the point: a false positive
 * is visible in the app, but a false negative only shows up as an
 * eventful-looking play with nothing beside it.
 *
 * Suppressions are marked distinctly from blanks, because "we decided not to"
 * and "we did not see it" are different failures:
 *
 *   CALL   the card was called
 *   SUGG   offered to the Ref as a suggestion
 *   ~sup~  recognised and deliberately held back (redundancy, negation, kick
 *          distance) — the rule that did it is named
 *   (none) the detector saw nothing at all
 *
 * The transcript is generated by this process, running the same ReplayFeed and
 * the same detector the server runs, at the same speed. It is a parallel run
 * rather than a recording of the server's own events, so the two can drift by a
 * second or two in wall-clock; the CONTENT of each line is what matters and
 * that is identical.
 */
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { io } from 'socket.io-client';

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { ReplayFeed } = require(path.join(ROOT, 'server/feed/replay-feed.js'));
const { explainPlay, detectDrive } = require(path.join(ROOT, 'server/feed/detect.js'));
const { modeFor } = require(path.join(ROOT, 'server/feed/cards.js'));

// ── arguments ──────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const flag = (name, fallback = null) => {
  const at = args.indexOf(`--${name}`);
  return at >= 0 && args[at + 1] ? args[at + 1] : fallback;
};
const fixturePath = args.find((a) => !a.startsWith('--') && a.endsWith('.json'));
const speed = Number(flag('speed', '1')) || 1;
const url = flag('url', 'http://127.0.0.1:3002');

if (!fixturePath) {
  console.error('usage: watch-replay.mjs <fixture.json> [--speed N] [--url URL]');
  process.exit(2);
}

const fixture = JSON.parse(fs.readFileSync(path.resolve(ROOT, fixturePath), 'utf8'));
const plays = [...(fixture.plays || [])].sort((a, b) => (a.sequence || 0) - (b.sequence || 0));
const drivesById = new Map((fixture.drives || []).map((d) => [String(d.id), d]));

// ── the server must already be up, with the seam on ────────────────────────
const die = (...lines) => { lines.forEach((l) => console.error(l)); process.exit(1); };

const checkServer = async () => {
  let res;
  try {
    res = await fetch(`${url}/socket.io/?EIO=4&transport=polling`, { signal: AbortSignal.timeout(4000) });
  } catch (error) {
    die(
      `✖ No server answering on ${url} (${error.message}).`,
      '',
      '  Start it yourself, with the replay seam on:',
      '',
      '      ALLOW_REPLAY_ATTACH=1 PORT=3002 node server.js',
      '',
      '  This script will not start it for you — a server it started would',
      '  disappear with it, and you are going to be watching for a while.'
    );
  }
  if (!res.ok) die(`✖ ${url} answered ${res.status} on the socket.io endpoint. Is that the game server?`);

  // The seam is server-side and not introspectable over HTTP, so prove it by
  // trying an attach that only succeeds when it is on.
  //
  // `gameAttached` is broadcast to the ROOM, so the socket that waits for it
  // has to be the one in the room — the prober — while a SECOND socket, which
  // holds no whistle, does the attaching. That is exactly the permission the
  // seam grants.
  const probe = io(url, { transports: ['polling'], reconnection: false });
  let attacker = null;
  const verdict = await new Promise((resolve) => {
    const done = (v) => resolve(v);
    probe.on('connect_error', () => done('unreachable'));
    probe.once('connect', () => {
      probe.once('roomCreated', (code) => {
        probe.once('gameAttached', () => done('on'));
        attacker = io(url, { transports: ['polling'], reconnection: false });
        attacker.once('connect', () => {
          attacker.emit('attachGame', {
            roomCode: code, league: 'nfl', gameId: 'seam-probe',
            replayFixture: { league: 'nfl', gameId: 'seam-probe', plays: [], drives: [] },
            speed: 1,
          });
          setTimeout(() => done('off'), 2500);
        });
      });
      probe.emit('createRoom', 'seam-probe');
    });
    setTimeout(() => done('timeout'), 10000);
  });
  probe.close();
  if (attacker) attacker.close();

  if (verdict === 'off') {
    die(
      '✖ The server is up but ALLOW_REPLAY_ATTACH is not set.',
      '',
      '  Restart it as:',
      '',
      '      ALLOW_REPLAY_ATTACH=1 PORT=3002 node server.js',
      '',
      '  Without the seam this script cannot attach a fixture to a room it does',
      '  not hold the whistle for.'
    );
  }
  if (verdict !== 'on') die(`✖ Could not confirm the server at ${url} (${verdict}).`);
};

// ── the transcript ─────────────────────────────────────────────────────────
// Opened only once the checks have passed, so a failed run leaves no empty file
// behind to be mistaken for a real one.
let transcriptPath = null;
let out = null;

const openTranscript = () => {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const transcriptDir = path.join(ROOT, 'transcripts');
  fs.mkdirSync(transcriptDir, { recursive: true });
  transcriptPath = path.join(transcriptDir, `${fixture.league}-${fixture.gameId}-${stamp}.txt`);
  out = fs.createWriteStream(transcriptPath, { flags: 'a' });
  writeHeader();
};

const pad = (v, n) => String(v ?? '').padEnd(n).slice(0, n);
/** Pad to a column, but NEVER truncate: the raw play text is the evidence. */
const col = (v, n) => {
  const str = String(v ?? '');
  return str.length >= n ? `${str}  ` : str.padEnd(n);
};
const clockOf = (p) => `Q${p.period ?? '?'} ${p.clock?.display ?? '--:--'}`;
const downOf = (p) => {
  const { down, distance } = p.start || {};
  if (down === null || down === undefined || down < 1) return '';
  const ord = { 1: '1st', 2: '2nd', 3: '3rd', 4: '4th' }[down] || `${down}th`;
  return distance === 0 ? `${ord} & goal` : `${ord} & ${distance}`;
};
const teamName = (id) => {
  const team = (fixture.teams || []).find((t) => String(t.id) === String(id));
  return team?.abbreviation || (id ? `#${id}` : '');
};

const writeHeader = () => {
out.write(`Shotgun Formation — replay transcript\n`);
out.write(`${fixture.name}  (${fixture.league} ${fixture.gameId})\n`);
out.write(`${plays.length} plays, replayed at ${speed}x, started ${new Date().toISOString()}\n`);
out.write(`\nOne line per play. Blank means the detector saw nothing — those are the\n`);
out.write(`lines to scan. "~sup~" means recognised and deliberately held back, with\n`);
out.write(`the rule named; that is different from blank and must not be read as one.\n`);
out.write(`${'='.repeat(150)}\n`);
out.write(`${pad('CLOCK', 10)}${pad('DOWN', 12)}${pad('POSS', 6)}${pad('PLAY', 104)}DETECTOR\n`);
out.write(`${'-'.repeat(150)}\n`);
};

let lineCount = 0;
let calledCount = 0;
let suppressedCount = 0;
let blankCount = 0;

const writePlay = (play) => {
  const { called, suppressed } = explainPlay(play, { league: fixture.league });
  const bits = [];
  for (const c of called) {
    bits.push(`${modeFor(c.cardId) === 'auto' ? 'CALL' : 'SUGG'} ${c.cardId} — ${c.reason}`);
  }
  for (const sup of suppressed) {
    bits.push(`~sup~ ${sup.cardId} [${sup.rule}] — ${sup.reason}`);
  }

  calledCount += called.length;
  suppressedCount += suppressed.length;
  if (!bits.length) blankCount += 1;
  lineCount += 1;

  const text = (play.text || play.shortText || '').replace(/\s+/g, ' ').trim();
  const head = `${pad(clockOf(play), 10)}${pad(downOf(play), 12)}${pad(teamName(play.start?.teamId), 6)}${col(text, 104)}`;
  out.write(`${head}${bits[0] || ''}\n`);
  // Extra cards from one play go underneath, indented, so the play stays one row.
  for (const extra of bits.slice(1)) out.write(`${' '.repeat(132)}${extra}\n`);
};

const writeDrive = (drive) => {
  for (const c of detectDrive(drive)) {
    out.write(`${pad('', 10)}${pad('[drive]', 12)}${pad(teamName(drive.teamId), 6)}`
      + `${col(`drive ended: ${drive.displayResult} (${drive.offensivePlays} plays, ${drive.yards} yds)`, 104)}`
      + `${modeFor(c.cardId) === 'auto' ? 'CALL' : 'SUGG'} ${c.cardId} — ${c.reason}\n`);
    calledCount += 1;
  }
};

// ── three windows, tiled ───────────────────────────────────────────────────
const WIDTH = 620;
const HEIGHT = 900;
const positions = [[0, 0], [WIDTH + 10, 0], [(WIDTH + 10) * 2, 0]];
const NAMES = ['Ref', 'Ben', 'Cy'];

const openWindow = async (index) => {
  const [x, y] = positions[index];
  const browser = await chromium.launch({
    headless: false,
    args: [`--window-position=${x},${y}`, `--window-size=${WIDTH},${HEIGHT}`],
  });
  const page = await browser.newPage({ viewport: { width: WIDTH - 20, height: HEIGHT - 120 } });
  page.on('dialog', (d) => d.accept());
  await page.goto(url, { waitUntil: 'load' });
  return { browser, page };
};

const run = async () => {
  await checkServer();
  openTranscript();

  console.log(`▶ ${fixture.name} (${fixture.league} ${fixture.gameId})`);
  console.log(`  ${plays.length} plays at ${speed}x`);
  console.log(`  opening three windows…\n`);

  const windows = [];
  for (let i = 0; i < NAMES.length; i += 1) windows.push(await openWindow(i));
  const [ref, ben, cy] = windows;

  // Window 1 creates the room and becomes the Ref.
  await ref.page.getByPlaceholder('Name').fill(NAMES[0]);
  await ref.page.getByRole('button', { name: 'Create a new game' }).click();
  const codeEl = ref.page.locator('.roomcode .n');
  try {
    await codeEl.waitFor({ timeout: 15000 });
  } catch {
    // Nearly always the same cause: the SERVED BUNDLE points at a different
    // server than the one this script checked. `client/.env.local` is baked in
    // at build time, so editing it without rebuilding leaves a bundle talking
    // to yesterday's address while the page looks perfectly fine.
    const target = await ref.page.evaluate(() => {
      const scripts = [...document.querySelectorAll('script[src]')].map((s) => s.src);
      return scripts.join(' ');
    }).catch(() => '');
    die(
      '✖ The room never appeared: the app did not reach the server.',
      '',
      `  This script is talking to ${url}, but the BUILT BUNDLE has its own`,
      '  address compiled in from client/.env.local at build time.',
      '',
      '  Rebuild the client so the two agree:',
      '',
      '      cat client/.env.local          # should be REACT_APP_API_URL=http://localhost:3002',
      '      cd client && npx react-scripts build',
      '',
      `  (loaded: ${target.slice(0, 120)})`
    );
  }
  const roomCode = (await codeEl.innerText()).trim();
  console.log(`  room ${roomCode} created by ${NAMES[0]}`);

  // The other two join. Three is the minimum to start, which is exactly what
  // three windows gives us.
  for (const [i, w] of [[1, ben], [2, cy]]) {
    await w.page.getByPlaceholder('Name').fill(NAMES[i]);
    await w.page.getByPlaceholder('5 digits').fill(roomCode);
    await w.page.getByRole('button', { name: /Join/ }).first().click();
    await w.page.waitForTimeout(600);
    console.log(`  ${NAMES[i]} joined`);
  }

  const start = ref.page.getByRole('button', { name: 'Start game' });
  await start.waitFor({ timeout: 15000 });
  for (let i = 0; i < 20 && await start.isDisabled(); i += 1) await ref.page.waitForTimeout(500);
  await start.click();
  await ref.page.waitForTimeout(1200);
  console.log(`  game started\n`);

  // Attach the fixture to that room, through the same seam replay-into-room uses.
  const socket = io(url, { transports: ['polling', 'websocket'], tryAllTransports: true, reconnection: false });
  await new Promise((resolve) => socket.on('connect', resolve));
  socket.emit('attachGame', {
    roomCode, league: fixture.league, gameId: String(fixture.gameId),
    replayFixture: fixture, speed,
  });
  await new Promise((resolve) => { socket.once('gameAttached', resolve); setTimeout(resolve, 4000); });
  console.log(`  replay attached — watch the windows; transcript is filling at:`);
  console.log(`  ${transcriptPath}\n`);

  // Our own pass over the same fixture at the same speed, for the transcript.
  const feed = new ReplayFeed(fixture, { speed });
  feed.on('play', (play) => {
    writePlay(play);
    if (lineCount % 25 === 0) process.stdout.write(`  …${lineCount}/${plays.length} plays\n`);
  });
  feed.on('drive', writeDrive);

  const finish = (why) => {
    out.write(`${'-'.repeat(150)}\n`);
    out.write(`${lineCount} plays · ${calledCount} called · ${suppressedCount} recognised-and-suppressed · ${blankCount} produced nothing\n`);
    out.write(`ended: ${why}\n`);
    out.end();

    const espn = `https://www.espn.com/${fixture.league === 'nfl' ? 'nfl' : 'college-football'}/playbyplay/_/gameId/${fixture.gameId}`;
    console.log(`\n■ ${why}`);
    console.log(`  ${lineCount} plays · ${calledCount} called · ${suppressedCount} suppressed · ${blankCount} blank`);
    console.log(`\n  transcript : ${transcriptPath}`);
    console.log(`  cross-check: ${espn}\n`);
    console.log('  Windows are still open. Ctrl-C here, or close them, when you are done.');
  };

  feed.on('end', ({ reason }) => finish(`feed ${reason}`));
  feed.start();

  // Stay open until the operator says otherwise.
  const shutdown = async () => {
    try { socket.emit('detachGame', { roomCode }); } catch { /* going away anyway */ }
    for (const w of windows) { try { await w.browser.close(); } catch { /* already gone */ } }
    process.exit(0);
  };
  process.on('SIGINT', () => { console.log('\nclosing…'); shutdown(); });
  for (const w of windows) w.browser.on('disconnected', () => shutdown());
};

run().catch((error) => {
  console.error(`✖ ${error.message}`);
  process.exit(1);
});
